spring:
  application:
    name: api

  profiles:
    default: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}
  admin-key: ${KAKAO_ADMIN_KEY}

tracking:
  stream-key: ${TRACKING_STREAM_KEY}
  consumer-group: ${TRACKING_CONSUMER_GROUP}

test:
  secret-key: ${TEST_SECRET_KEY}
firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-flat-param-object: true

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  public-url: ${MINIO_PUBLIC_URL}
