apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/network-policy.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
images:
  - name: ghcr.io/semosan/semosan_be
    newTag: 8b93b305eb5dc06e2a88f8b3ceda17de013340a0
