apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
images:
  - name: ghcr.io/semosan/semosan_be
    newTag: f8858b7d3376f095e18c59eb3dbbc41aedf639d9
