apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
images:
  - name: ghcr.io/semosan/semosan_be
    newTag: 2408eb0c0f5fc413f174a8745cfd08f32d7a88ce
