default-nickname.adjectives=용감한,씩씩한,빠른,느긋한,신나는,가벼운,든든한,활발한,여유로운,상쾌한,푸른,맑은,밝은,멋진,즐거운,힘찬,건강한,차분한,따뜻한,반가운
default-nickname.nouns=등산러,산악인,하이커,산꾼,등반가,산사람,트레커,산행러,정상러,탐방러,능선러,둘레러,백패커,산친구,봉우리,숲길러,오름러,길잡이,바위러,피크러
