apiVersion: apps/v1
kind: Deployment
metadata:
  name: semosan-api
  namespace: semosan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semosan-api
  template:
    metadata:
      labels:
        app: semosan-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: semosan-api
          image: ghcr.io/semosan/semosan_be:88c9467c40d8d7be2080b78d68e54b3d6c2ea2ce
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_PATH
              value: /etc/firebase/firebase-service-account.json
          volumeMounts:
            - name: firebase-secret
              mountPath: /etc/firebase
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-secret