apiVersion: apps/v1
kind: Deployment
metadata:
  name: semosan-api
  namespace: semosan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semosan-api
  template:
    metadata:
      labels:
        app: semosan-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: semosan-api
          image: ghcr.io/semosan/semosan_be:96414254612fd6667dbf9ef41845130662eade5f
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30