-- =====================================================================
-- V10__create_tracking_photos.sql
-- 목적: 트래킹 마일스톤 사진 메타 저장 테이블 생성.
--        실제 이미지 바이너리는 MinIO 에 보관되고 본 테이블엔 URL 만 저장.
--        + notifications.type CHECK 제약 갱신 (TRACKING_PHOTO_MILESTONE 추가)
-- =====================================================================

CREATE TABLE IF NOT EXISTS tracking_photos
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    tracking_session_id  bigint not null
        constraint fk_tracking_photos_session
            references tracking_sessions,
    milestone_index      integer not null,
    milestone_distance_m double precision not null,
    image_url            varchar(500) not null,
    captured_at          timestamp(6) not null,
    lat                  double precision not null,
    lng                  double precision not null,
    altitude             double precision
);

CREATE INDEX IF NOT EXISTS idx_tracking_photos_session
    ON tracking_photos (tracking_session_id);

CREATE INDEX IF NOT EXISTS idx_tracking_photos_session_milestone
    ON tracking_photos (tracking_session_id, milestone_index);

-- =====================================================================
-- notifications.type CHECK 제약 갱신.
-- Hibernate 가 enum 컬럼 생성 시점의 값만으로 CHECK 를 만들고
-- 새 enum 값 추가 시 자동 갱신하지 않으므로 수동 갱신 필요.
-- 새 enum 값 추가 시 동일 패턴으로 갱신.
-- =====================================================================
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
    CHECK (type IN ('COMMUNITY_COMMENT', 'TRACKING_PHOTO_MILESTONE'));
