CREATE TABLE IF NOT EXISTS course_difficulty_feedbacks
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    hiking_record_id  bigint       not null
        constraint uk_course_difficulty_feedback_hiking_record
            unique
        constraint fk_course_difficulty_feedback_hiking_record
            references hiking_records,
    user_id           bigint       not null
        constraint fk_course_difficulty_feedback_user
            references users,
    mountain_id       bigint       not null
        constraint fk_course_difficulty_feedback_mountain
            references mountains,
    course_id         bigint       not null
        constraint fk_course_difficulty_feedback_course
            references courses,
    guide_difficulty  varchar(20)  not null
        constraint course_difficulty_feedbacks_guide_difficulty_check
            check ((guide_difficulty)::text = ANY
                   ((ARRAY ['EASY'::character varying, 'NORMAL'::character varying, 'HARD'::character varying])::text[])),
    comparison        varchar(20)  not null
        constraint course_difficulty_feedbacks_comparison_check
            check ((comparison)::text = ANY
                   ((ARRAY ['SIMILAR'::character varying, 'EASIER'::character varying, 'HARDER'::character varying])::text[]))
);

CREATE INDEX IF NOT EXISTS idx_course_difficulty_feedback_course_id
    ON course_difficulty_feedbacks (course_id);

CREATE INDEX IF NOT EXISTS idx_course_difficulty_feedback_user_id
    ON course_difficulty_feedbacks (user_id);
