CREATE TABLE IF NOT EXISTS free_post_reports
(
    id          bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    reporter_id  bigint       not null
        constraint fk_free_post_reports_reporter
            references users,
    post_id      bigint       not null
        constraint fk_free_post_reports_post
            references free_posts,
    reason       varchar(30)  not null,
    constraint uk_free_post_reports_reporter_post
        unique (reporter_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_free_post_reports_post_id
    ON free_post_reports (post_id);

CREATE INDEX IF NOT EXISTS idx_free_post_reports_reporter_id
    ON free_post_reports (reporter_id);
