CREATE TABLE IF NOT EXISTS user_blocks
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    blocker_id       bigint       not null
        constraint fk_user_blocks_blocker
            references users,
    blocked_user_id  bigint       not null
        constraint fk_user_blocks_blocked_user
            references users,
    constraint uk_user_blocks_blocker_blocked
        unique (blocker_id, blocked_user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_blocks_blocker_id
    ON user_blocks (blocker_id);

CREATE INDEX IF NOT EXISTS idx_user_blocks_blocked_user_id
    ON user_blocks (blocked_user_id);
