CREATE TABLE IF NOT EXISTS course_likes
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fk_course_likes_user
            references users,
    course_id  bigint       not null
        constraint fk_course_likes_course
            references courses,
    constraint uk_course_likes_user_id_course_id
        unique (user_id, course_id)
);

CREATE INDEX IF NOT EXISTS idx_course_likes_user_id_created_at
    on course_likes (user_id asc, created_at desc);
