-- =====================================================================
-- V6__create_tracking_sessions.sql
-- 목적: 트래킹 세션 도메인용 tracking_sessions 테이블 생성
-- =====================================================================

CREATE TABLE IF NOT EXISTS tracking_sessions
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    user_id              bigint not null
        constraint fk_tracking_sessions_user
            references users,
    mountain_id          bigint not null
        constraint fk_tracking_sessions_mountain
            references mountains,
    course_id            bigint
        constraint fk_tracking_sessions_course
            references courses,
    is_free_recording    boolean not null,
    status               varchar(20) not null
        constraint tracking_sessions_status_check
            check (status in ('IN_PROGRESS', 'PAUSED', 'COMPLETED', 'ABANDONED')),
    started_at           timestamp(6) not null,
    ended_at             timestamp(6),
    paused_at            timestamp(6),
    paused_seconds_total integer not null
);

-- 유저별 활성 세션 조회 (existsByUser_IdAndStatusIn, findFirstByUser_IdAndStatusIn...)
CREATE INDEX IF NOT EXISTS idx_tracking_sessions_user_status
    ON tracking_sessions (user_id, status);

-- 24h 자동 만료 스케줄러 (status IN AND updated_at <)
CREATE INDEX IF NOT EXISTS idx_tracking_sessions_status_updated_at
    ON tracking_sessions (status, updated_at);
