-- =====================================================================
-- V8__create_tracking_points.sql
-- 목적: 트래킹 세션이 누적한 GPS 점(tracking_points) 테이블 생성
-- =====================================================================

CREATE TABLE IF NOT EXISTS tracking_points
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    tracking_session_id bigint not null
        constraint fk_tracking_points_session
            references tracking_sessions,
    location            geography(Point, 4326) not null,
    altitude            double precision,
    recorded_at         timestamp(6) not null
);

-- 세션별 시간순 GPS 점 조회 (트래킹 종료 시 통계/이력 계산)
CREATE INDEX IF NOT EXISTS idx_tracking_points_session_recorded
    ON tracking_points (tracking_session_id, recorded_at);
